//----------------------------------------------------------------------
//   THIS IS AUTOMATICALLY GENERATED CODE
//   Generated by Mentor Graphics' Register Assistant UVM V2020.4 (Build 1)
//   UVM Register Kit version 1.1
//----------------------------------------------------------------------
// Project         : csvFiles
// Unit            : top_psif_vreguvm_pkg_uvm_rw
// File            : top_psif_vreguvm_pkg_uvm_rw.sv
//----------------------------------------------------------------------
// Created by      : mohammzf
// Creation Date   : 10/3/23 10:48 AM
//----------------------------------------------------------------------
// Title           : csvFiles
//
// Description     : 
//
//----------------------------------------------------------------------

//----------------------------------------------------------------------
// top_psif_vreguvm_pkg_uvm_rw
//----------------------------------------------------------------------
package top_psif_vreguvm_pkg_uvm_rw;

   import uvm_pkg::*;

   `include "uvm_macros.svh"

   /* DEFINE REGISTER CLASSES */



   //--------------------------------------------------------------------
   // Class: AUI_AURORA_ACCESS_LOOP_ENA_reg
   // 
   //--------------------------------------------------------------------

   class AUI_AURORA_ACCESS_LOOP_ENA_reg extends uvm_reg;
      `uvm_object_utils(AUI_AURORA_ACCESS_LOOP_ENA_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "AUI_AURORA_ACCESS_LOOP_ENA_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: AUI_AURORA_FIFO_TX_WRITE_ENABLE_reg
   // 
   //--------------------------------------------------------------------

   class AUI_AURORA_FIFO_TX_WRITE_ENABLE_reg extends uvm_reg;
      `uvm_object_utils(AUI_AURORA_FIFO_TX_WRITE_ENABLE_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "AUI_AURORA_FIFO_TX_WRITE_ENABLE_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: AUI_AURORA_GT_RESET_reg
   // 
   //--------------------------------------------------------------------

   class AUI_AURORA_GT_RESET_reg extends uvm_reg;
      `uvm_object_utils(AUI_AURORA_GT_RESET_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "AUI_AURORA_GT_RESET_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b1, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: AUI_AURORA_LOOPBACK_reg
   // 
   //--------------------------------------------------------------------

   class AUI_AURORA_LOOPBACK_reg extends uvm_reg;
      `uvm_object_utils(AUI_AURORA_LOOPBACK_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[2:0];
      endgroup



      // Function: new
      // 
      function new(string name = "AUI_AURORA_LOOPBACK_reg");
         super.new(name, 3, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 3, 0, "RW", 0, 3'b000, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: AUI_AURORA_RESET_reg
   // 
   //--------------------------------------------------------------------

   class AUI_AURORA_RESET_reg extends uvm_reg;
      `uvm_object_utils(AUI_AURORA_RESET_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "AUI_AURORA_RESET_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b1, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: AUI_RESET_reg
   // 
   //--------------------------------------------------------------------

   class AUI_RESET_reg extends uvm_reg;
      `uvm_object_utils(AUI_RESET_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "AUI_RESET_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: DTI_SPI_FIFO_TX_WRITE_ENABLE_reg
   // 
   //--------------------------------------------------------------------

   class DTI_SPI_FIFO_TX_WRITE_ENABLE_reg extends uvm_reg;
      `uvm_object_utils(DTI_SPI_FIFO_TX_WRITE_ENABLE_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "DTI_SPI_FIFO_TX_WRITE_ENABLE_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b1, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: DTI_SPI_LOOP_ENA_reg
   // 
   //--------------------------------------------------------------------

   class DTI_SPI_LOOP_ENA_reg extends uvm_reg;
      `uvm_object_utils(DTI_SPI_LOOP_ENA_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "DTI_SPI_LOOP_ENA_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: DTI_SPI_PS_ACCESS_ENA_reg
   // 
   //--------------------------------------------------------------------

   class DTI_SPI_PS_ACCESS_ENA_reg extends uvm_reg;
      `uvm_object_utils(DTI_SPI_PS_ACCESS_ENA_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "DTI_SPI_PS_ACCESS_ENA_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ODI_OLEDBYTE11_8_reg
   // 
   //--------------------------------------------------------------------

   class ODI_OLEDBYTE11_8_reg extends uvm_reg;
      `uvm_object_utils(ODI_OLEDBYTE11_8_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "ODI_OLEDBYTE11_8_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 32, 0, "RW", 0, 32'h20202120, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ODI_OLEDBYTE15_12_reg
   // 
   //--------------------------------------------------------------------

   class ODI_OLEDBYTE15_12_reg extends uvm_reg;
      `uvm_object_utils(ODI_OLEDBYTE15_12_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "ODI_OLEDBYTE15_12_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 32, 0, "RW", 0, 32'h20202021, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ODI_OLEDBYTE3_0_reg
   // 
   //--------------------------------------------------------------------

   class ODI_OLEDBYTE3_0_reg extends uvm_reg;
      `uvm_object_utils(ODI_OLEDBYTE3_0_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "ODI_OLEDBYTE3_0_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 32, 0, "RW", 0, 32'h21202020, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ODI_OLEDBYTE7_4_reg
   // 
   //--------------------------------------------------------------------

   class ODI_OLEDBYTE7_4_reg extends uvm_reg;
      `uvm_object_utils(ODI_OLEDBYTE7_4_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "ODI_OLEDBYTE7_4_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 32, 0, "RW", 0, 32'h20212020, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ODI_PS_ACCESS_ENA_reg
   // 
   //--------------------------------------------------------------------

   class ODI_PS_ACCESS_ENA_reg extends uvm_reg;
      `uvm_object_utils(ODI_PS_ACCESS_ENA_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "ODI_PS_ACCESS_ENA_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_DTI_READ_ENA_reg
   // 
   //--------------------------------------------------------------------

   class SCU_DTI_READ_ENA_reg extends uvm_reg;
      `uvm_object_utils(SCU_DTI_READ_ENA_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_DTI_READ_ENA_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_FSM_RST_reg
   // 
   //--------------------------------------------------------------------

   class SCU_FSM_RST_reg extends uvm_reg;
      `uvm_object_utils(SCU_FSM_RST_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_FSM_RST_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_OLEDBYTE11_8_reg
   // 
   //--------------------------------------------------------------------

   class SCU_OLEDBYTE11_8_reg extends uvm_reg;
      `uvm_object_utils(SCU_OLEDBYTE11_8_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_OLEDBYTE11_8_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_OLEDBYTE15_12_reg
   // 
   //--------------------------------------------------------------------

   class SCU_OLEDBYTE15_12_reg extends uvm_reg;
      `uvm_object_utils(SCU_OLEDBYTE15_12_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_OLEDBYTE15_12_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_OLEDBYTE3_0_reg
   // 
   //--------------------------------------------------------------------

   class SCU_OLEDBYTE3_0_reg extends uvm_reg;
      `uvm_object_utils(SCU_OLEDBYTE3_0_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_OLEDBYTE3_0_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_OLEDBYTE7_4_reg
   // 
   //--------------------------------------------------------------------

   class SCU_OLEDBYTE7_4_reg extends uvm_reg;
      `uvm_object_utils(SCU_OLEDBYTE7_4_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[31:0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_OLEDBYTE7_4_reg");
         super.new(name, 32, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 32, 0, "RW", 0, 32'h00000000, 1, 1, 1);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_TEMPERATURE_TEST_DIGIT0_reg
   // 
   //--------------------------------------------------------------------

   class SCU_TEMPERATURE_TEST_DIGIT0_reg extends uvm_reg;
      `uvm_object_utils(SCU_TEMPERATURE_TEST_DIGIT0_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[3:0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_TEMPERATURE_TEST_DIGIT0_reg");
         super.new(name, 4, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 4, 0, "RW", 0, 4'h0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_TEMPERATURE_TEST_DIGIT1_reg
   // 
   //--------------------------------------------------------------------

   class SCU_TEMPERATURE_TEST_DIGIT1_reg extends uvm_reg;
      `uvm_object_utils(SCU_TEMPERATURE_TEST_DIGIT1_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[3:0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_TEMPERATURE_TEST_DIGIT1_reg");
         super.new(name, 4, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 4, 0, "RW", 0, 4'h0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_TEMPERATURE_TEST_ENA_reg
   // 
   //--------------------------------------------------------------------

   class SCU_TEMPERATURE_TEST_ENA_reg extends uvm_reg;
      `uvm_object_utils(SCU_TEMPERATURE_TEST_ENA_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_TEMPERATURE_TEST_ENA_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: SCU_ZU_DATA_ENA_reg
   // 
   //--------------------------------------------------------------------

   class SCU_ZU_DATA_ENA_reg extends uvm_reg;
      `uvm_object_utils(SCU_ZU_DATA_ENA_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "SCU_ZU_DATA_ENA_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ZUKEY_mem
   // 
   //--------------------------------------------------------------------

   class ZUKEY_mem extends uvm_mem;
      `uvm_object_utils(ZUKEY_mem)



      // Function: new
      // 
      function new(string name = "ZUKEY_mem");
         super.new(name, 'h200, 32, "RW", UVM_NO_COVERAGE);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ZUPACKET_mem
   // 
   //--------------------------------------------------------------------

   class ZUPACKET_mem extends uvm_mem;
      `uvm_object_utils(ZUPACKET_mem)



      // Function: new
      // 
      function new(string name = "ZUPACKET_mem");
         super.new(name, 'h200, 32, "RW", UVM_NO_COVERAGE);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ZU_DECRYPTION_BYPASS_reg
   // 
   // Data  packet  NOT  decrypted;  just  passed  through
   //--------------------------------------------------------------------

   class ZU_DECRYPTION_BYPASS_reg extends uvm_reg;
      `uvm_object_utils(ZU_DECRYPTION_BYPASS_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "ZU_DECRYPTION_BYPASS_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b1, 1, 1, 0);
      endfunction
   endclass



   //--------------------------------------------------------------------
   // Class: ZU_FSM_RST_reg
   // 
   // Reset  ZU  FSM  that  controls  decryption  HLS  IP.
   //--------------------------------------------------------------------

   class ZU_FSM_RST_reg extends uvm_reg;
      `uvm_object_utils(ZU_FSM_RST_reg)

      rand uvm_reg_field data; 


      // Function: coverage
      // 
      covergroup cg_vals;
         data	 : coverpoint data.value[0];
      endgroup



      // Function: new
      // 
      function new(string name = "ZU_FSM_RST_reg");
         super.new(name, 1, build_coverage(UVM_CVR_FIELD_VALS));
         add_coverage(build_coverage(UVM_CVR_FIELD_VALS));
         if(has_coverage(UVM_CVR_FIELD_VALS))
            cg_vals = new();
      endfunction


      // Function: sample_values
      // 
      virtual function void sample_values();
         super.sample_values();
         if (get_coverage(UVM_CVR_FIELD_VALS))
            cg_vals.sample();
      endfunction


      // Function: build
      // 
      virtual function void build();
         data = uvm_reg_field::type_id::create("data");

         data.configure(this, 1, 0, "RW", 0, 1'b0, 1, 1, 0);
      endfunction
   endclass




   /* BLOCKS */



   //--------------------------------------------------------------------
   // Class: ODI_module_ODI_map_coverage
   // 
   // Coverage for the 'ODI_map' in 'ODI_module'
   //--------------------------------------------------------------------

   class ODI_module_ODI_map_coverage extends uvm_object;
      `uvm_object_utils(ODI_module_ODI_map_coverage)

      covergroup ra_cov(string name) with function sample(uvm_reg_addr_t addr, bit is_read);

         option.per_instance = 1;
         option.name = name; 

         ADDR: coverpoint addr {
            bins ODI_OLEDBYTE3_0 = {'h60};
            bins ODI_OLEDBYTE7_4 = {'h64};
            bins ODI_OLEDBYTE11_8 = {'h68};
            bins ODI_OLEDBYTE15_12 = {'h6c};
            bins ODI_PS_ACCESS_ENA = {'h88};
         }

         RW: coverpoint is_read {
            bins RD = {1};
            bins WR = {0};
         }

         ACCESS: cross ADDR, RW;

      endgroup: ra_cov

      function new(string name = "ODI_module_ODI_map_coverage");
         ra_cov = new(name);
      endfunction: new

      function void sample(uvm_reg_addr_t offset, bit is_read);
         ra_cov.sample(offset, is_read);
      endfunction: sample

   endclass: ODI_module_ODI_map_coverage



   //--------------------------------------------------------------------
   // Class: ODI_module
   // 
   // Block  registers
   //--------------------------------------------------------------------

   class ODI_module extends uvm_reg_block;
      `uvm_object_utils(ODI_module)

      rand ODI_OLEDBYTE3_0_reg ODI_OLEDBYTE3_0; 
      rand ODI_OLEDBYTE7_4_reg ODI_OLEDBYTE7_4; 
      rand ODI_OLEDBYTE11_8_reg ODI_OLEDBYTE11_8; 
      rand ODI_OLEDBYTE15_12_reg ODI_OLEDBYTE15_12; 
      rand ODI_PS_ACCESS_ENA_reg ODI_PS_ACCESS_ENA; 

      uvm_reg_map ODI_map; 
      ODI_module_ODI_map_coverage ODI_map_cg;


      // Function: new
      // 
      function new(string name = "ODI_module");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();

         if(has_coverage(UVM_CVR_ADDR_MAP)) begin
            ODI_map_cg = ODI_module_ODI_map_coverage::type_id::create("ODI_map_cg");
            ODI_map_cg.ra_cov.set_inst_name(this.get_full_name());
            void'(set_coverage(UVM_CVR_ADDR_MAP));
         end
         ODI_OLEDBYTE3_0 = ODI_OLEDBYTE3_0_reg::type_id::create("ODI_OLEDBYTE3_0");
         ODI_OLEDBYTE3_0.configure(this);
         ODI_OLEDBYTE3_0.build();

         ODI_OLEDBYTE7_4 = ODI_OLEDBYTE7_4_reg::type_id::create("ODI_OLEDBYTE7_4");
         ODI_OLEDBYTE7_4.configure(this);
         ODI_OLEDBYTE7_4.build();

         ODI_OLEDBYTE11_8 = ODI_OLEDBYTE11_8_reg::type_id::create("ODI_OLEDBYTE11_8");
         ODI_OLEDBYTE11_8.configure(this);
         ODI_OLEDBYTE11_8.build();

         ODI_OLEDBYTE15_12 = ODI_OLEDBYTE15_12_reg::type_id::create("ODI_OLEDBYTE15_12");
         ODI_OLEDBYTE15_12.configure(this);
         ODI_OLEDBYTE15_12.build();

         ODI_PS_ACCESS_ENA = ODI_PS_ACCESS_ENA_reg::type_id::create("ODI_PS_ACCESS_ENA");
         ODI_PS_ACCESS_ENA.configure(this);
         ODI_PS_ACCESS_ENA.build();

         ODI_map = create_map("ODI_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = ODI_map;

         ODI_map.add_reg(ODI_OLEDBYTE3_0, 'h60, "RW");
         ODI_map.add_reg(ODI_OLEDBYTE7_4, 'h64, "RW");
         ODI_map.add_reg(ODI_OLEDBYTE11_8, 'h68, "RW");
         ODI_map.add_reg(ODI_OLEDBYTE15_12, 'h6c, "RW");
         ODI_map.add_reg(ODI_PS_ACCESS_ENA, 'h88, "RW");

         lock_model();
      endfunction


      // Function: sample
      // 
      function void sample(uvm_reg_addr_t offset, bit is_read, uvm_reg_map  map);
         if(get_coverage(UVM_CVR_ADDR_MAP)) begin
            if(map.get_name() == "ODI_map") begin
               ODI_map_cg.sample(offset, is_read);
            end
         end
      endfunction: sample

   endclass



   //--------------------------------------------------------------------
   // Class: DTI_module_DTI_map_coverage
   // 
   // Coverage for the 'DTI_map' in 'DTI_module'
   //--------------------------------------------------------------------

   class DTI_module_DTI_map_coverage extends uvm_object;
      `uvm_object_utils(DTI_module_DTI_map_coverage)

      covergroup ra_cov(string name) with function sample(uvm_reg_addr_t addr, bit is_read);

         option.per_instance = 1;
         option.name = name; 

         ADDR: coverpoint addr {
            bins DTI_SPI_FIFO_TX_WRITE_ENABLE = {'h60};
            bins DTI_SPI_LOOP_ENA = {'h70};
            bins DTI_SPI_PS_ACCESS_ENA = {'h74};
         }

         RW: coverpoint is_read {
            bins RD = {1};
            bins WR = {0};
         }

         ACCESS: cross ADDR, RW;

      endgroup: ra_cov

      function new(string name = "DTI_module_DTI_map_coverage");
         ra_cov = new(name);
      endfunction: new

      function void sample(uvm_reg_addr_t offset, bit is_read);
         ra_cov.sample(offset, is_read);
      endfunction: sample

   endclass: DTI_module_DTI_map_coverage



   //--------------------------------------------------------------------
   // Class: DTI_module
   // 
   // Block  registers
   //--------------------------------------------------------------------

   class DTI_module extends uvm_reg_block;
      `uvm_object_utils(DTI_module)

      rand DTI_SPI_FIFO_TX_WRITE_ENABLE_reg DTI_SPI_FIFO_TX_WRITE_ENABLE; 
      rand DTI_SPI_LOOP_ENA_reg DTI_SPI_LOOP_ENA; 
      rand DTI_SPI_PS_ACCESS_ENA_reg DTI_SPI_PS_ACCESS_ENA; 

      uvm_reg_map DTI_map; 
      DTI_module_DTI_map_coverage DTI_map_cg;


      // Function: new
      // 
      function new(string name = "DTI_module");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();

         if(has_coverage(UVM_CVR_ADDR_MAP)) begin
            DTI_map_cg = DTI_module_DTI_map_coverage::type_id::create("DTI_map_cg");
            DTI_map_cg.ra_cov.set_inst_name(this.get_full_name());
            void'(set_coverage(UVM_CVR_ADDR_MAP));
         end
         DTI_SPI_FIFO_TX_WRITE_ENABLE = DTI_SPI_FIFO_TX_WRITE_ENABLE_reg::type_id::create("DTI_SPI_FIFO_TX_WRITE_ENABLE");
         DTI_SPI_FIFO_TX_WRITE_ENABLE.configure(this);
         DTI_SPI_FIFO_TX_WRITE_ENABLE.build();

         DTI_SPI_LOOP_ENA = DTI_SPI_LOOP_ENA_reg::type_id::create("DTI_SPI_LOOP_ENA");
         DTI_SPI_LOOP_ENA.configure(this);
         DTI_SPI_LOOP_ENA.build();

         DTI_SPI_PS_ACCESS_ENA = DTI_SPI_PS_ACCESS_ENA_reg::type_id::create("DTI_SPI_PS_ACCESS_ENA");
         DTI_SPI_PS_ACCESS_ENA.configure(this);
         DTI_SPI_PS_ACCESS_ENA.build();

         DTI_map = create_map("DTI_map", 'h0, 1, UVM_LITTLE_ENDIAN, 1);
         default_map = DTI_map;

         DTI_map.add_reg(DTI_SPI_FIFO_TX_WRITE_ENABLE, 'h60, "RW");
         DTI_map.add_reg(DTI_SPI_LOOP_ENA, 'h70, "RW");
         DTI_map.add_reg(DTI_SPI_PS_ACCESS_ENA, 'h74, "RW");

         lock_model();
      endfunction


      // Function: sample
      // 
      function void sample(uvm_reg_addr_t offset, bit is_read, uvm_reg_map  map);
         if(get_coverage(UVM_CVR_ADDR_MAP)) begin
            if(map.get_name() == "DTI_map") begin
               DTI_map_cg.sample(offset, is_read);
            end
         end
      endfunction: sample

   endclass



   //--------------------------------------------------------------------
   // Class: ZU_module_ZU_map_coverage
   // 
   // Coverage for the 'ZU_map' in 'ZU_module'
   //--------------------------------------------------------------------

   class ZU_module_ZU_map_coverage extends uvm_object;
      `uvm_object_utils(ZU_module_ZU_map_coverage)

      covergroup ra_cov(string name) with function sample(uvm_reg_addr_t addr, bit is_read);

         option.per_instance = 1;
         option.name = name; 

         ADDR: coverpoint addr {
            bins ZU_DECRYPTION_BYPASS = {'h0};
            bins ZU_FSM_RST = {'hc};
         }

         RW: coverpoint is_read {
            bins RD = {1};
            bins WR = {0};
         }

         ACCESS: cross ADDR, RW;

      endgroup: ra_cov

      function new(string name = "ZU_module_ZU_map_coverage");
         ra_cov = new(name);
      endfunction: new

      function void sample(uvm_reg_addr_t offset, bit is_read);
         ra_cov.sample(offset, is_read);
      endfunction: sample

   endclass: ZU_module_ZU_map_coverage



   //--------------------------------------------------------------------
   // Class: ZU_module
   // 
   // Block  registers
   //--------------------------------------------------------------------

   class ZU_module extends uvm_reg_block;
      `uvm_object_utils(ZU_module)

      rand ZU_DECRYPTION_BYPASS_reg ZU_DECRYPTION_BYPASS; // Data  packet  NOT  decrypted;  just  passed  through
      rand ZU_FSM_RST_reg ZU_FSM_RST; // Reset  ZU  FSM  that  controls  decryption  HLS  IP.

      uvm_reg_map ZU_map; 
      ZU_module_ZU_map_coverage ZU_map_cg;


      // Function: new
      // 
      function new(string name = "ZU_module");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();

         if(has_coverage(UVM_CVR_ADDR_MAP)) begin
            ZU_map_cg = ZU_module_ZU_map_coverage::type_id::create("ZU_map_cg");
            ZU_map_cg.ra_cov.set_inst_name(this.get_full_name());
            void'(set_coverage(UVM_CVR_ADDR_MAP));
         end
         ZU_DECRYPTION_BYPASS = ZU_DECRYPTION_BYPASS_reg::type_id::create("ZU_DECRYPTION_BYPASS");
         ZU_DECRYPTION_BYPASS.configure(this);
         ZU_DECRYPTION_BYPASS.build();

         ZU_FSM_RST = ZU_FSM_RST_reg::type_id::create("ZU_FSM_RST");
         ZU_FSM_RST.configure(this);
         ZU_FSM_RST.build();

         ZU_map = create_map("ZU_map", 'h0, 1, UVM_LITTLE_ENDIAN, 1);
         default_map = ZU_map;

         ZU_map.add_reg(ZU_DECRYPTION_BYPASS, 'h0, "RW");
         ZU_map.add_reg(ZU_FSM_RST, 'hc, "RW");

         lock_model();
      endfunction


      // Function: sample
      // 
      function void sample(uvm_reg_addr_t offset, bit is_read, uvm_reg_map  map);
         if(get_coverage(UVM_CVR_ADDR_MAP)) begin
            if(map.get_name() == "ZU_map") begin
               ZU_map_cg.sample(offset, is_read);
            end
         end
      endfunction: sample

   endclass



   //--------------------------------------------------------------------
   // Class: SCU_module_SCU_map_coverage
   // 
   // Coverage for the 'SCU_map' in 'SCU_module'
   //--------------------------------------------------------------------

   class SCU_module_SCU_map_coverage extends uvm_object;
      `uvm_object_utils(SCU_module_SCU_map_coverage)

      covergroup ra_cov(string name) with function sample(uvm_reg_addr_t addr, bit is_read);

         option.per_instance = 1;
         option.name = name; 

         ADDR: coverpoint addr {
            bins SCU_ZU_DATA_ENA = {'h0};
            bins SCU_DTI_READ_ENA = {'h4};
            bins SCU_FSM_RST = {'h8};
            bins SCU_OLEDBYTE3_0 = {'h10};
            bins SCU_OLEDBYTE7_4 = {'h14};
            bins SCU_OLEDBYTE11_8 = {'h18};
            bins SCU_OLEDBYTE15_12 = {'h1c};
            bins SCU_TEMPERATURE_TEST_ENA = {'h28};
            bins SCU_TEMPERATURE_TEST_DIGIT0 = {'h2c};
            bins SCU_TEMPERATURE_TEST_DIGIT1 = {'h30};
         }

         RW: coverpoint is_read {
            bins RD = {1};
            bins WR = {0};
         }

         ACCESS: cross ADDR, RW;

      endgroup: ra_cov

      function new(string name = "SCU_module_SCU_map_coverage");
         ra_cov = new(name);
      endfunction: new

      function void sample(uvm_reg_addr_t offset, bit is_read);
         ra_cov.sample(offset, is_read);
      endfunction: sample

   endclass: SCU_module_SCU_map_coverage



   //--------------------------------------------------------------------
   // Class: SCU_module
   // 
   // Block  registers
   //--------------------------------------------------------------------

   class SCU_module extends uvm_reg_block;
      `uvm_object_utils(SCU_module)

      rand SCU_ZU_DATA_ENA_reg SCU_ZU_DATA_ENA; 
      rand SCU_DTI_READ_ENA_reg SCU_DTI_READ_ENA; 
      rand SCU_FSM_RST_reg SCU_FSM_RST; 
      rand SCU_OLEDBYTE3_0_reg SCU_OLEDBYTE3_0; 
      rand SCU_OLEDBYTE7_4_reg SCU_OLEDBYTE7_4; 
      rand SCU_OLEDBYTE11_8_reg SCU_OLEDBYTE11_8; 
      rand SCU_OLEDBYTE15_12_reg SCU_OLEDBYTE15_12; 
      rand SCU_TEMPERATURE_TEST_ENA_reg SCU_TEMPERATURE_TEST_ENA; 
      rand SCU_TEMPERATURE_TEST_DIGIT0_reg SCU_TEMPERATURE_TEST_DIGIT0; 
      rand SCU_TEMPERATURE_TEST_DIGIT1_reg SCU_TEMPERATURE_TEST_DIGIT1; 

      uvm_reg_map SCU_map; 
      SCU_module_SCU_map_coverage SCU_map_cg;


      // Function: new
      // 
      function new(string name = "SCU_module");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();

         if(has_coverage(UVM_CVR_ADDR_MAP)) begin
            SCU_map_cg = SCU_module_SCU_map_coverage::type_id::create("SCU_map_cg");
            SCU_map_cg.ra_cov.set_inst_name(this.get_full_name());
            void'(set_coverage(UVM_CVR_ADDR_MAP));
         end
         SCU_ZU_DATA_ENA = SCU_ZU_DATA_ENA_reg::type_id::create("SCU_ZU_DATA_ENA");
         SCU_ZU_DATA_ENA.configure(this);
         SCU_ZU_DATA_ENA.build();

         SCU_DTI_READ_ENA = SCU_DTI_READ_ENA_reg::type_id::create("SCU_DTI_READ_ENA");
         SCU_DTI_READ_ENA.configure(this);
         SCU_DTI_READ_ENA.build();

         SCU_FSM_RST = SCU_FSM_RST_reg::type_id::create("SCU_FSM_RST");
         SCU_FSM_RST.configure(this);
         SCU_FSM_RST.build();

         SCU_OLEDBYTE3_0 = SCU_OLEDBYTE3_0_reg::type_id::create("SCU_OLEDBYTE3_0");
         SCU_OLEDBYTE3_0.configure(this);
         SCU_OLEDBYTE3_0.build();

         SCU_OLEDBYTE7_4 = SCU_OLEDBYTE7_4_reg::type_id::create("SCU_OLEDBYTE7_4");
         SCU_OLEDBYTE7_4.configure(this);
         SCU_OLEDBYTE7_4.build();

         SCU_OLEDBYTE11_8 = SCU_OLEDBYTE11_8_reg::type_id::create("SCU_OLEDBYTE11_8");
         SCU_OLEDBYTE11_8.configure(this);
         SCU_OLEDBYTE11_8.build();

         SCU_OLEDBYTE15_12 = SCU_OLEDBYTE15_12_reg::type_id::create("SCU_OLEDBYTE15_12");
         SCU_OLEDBYTE15_12.configure(this);
         SCU_OLEDBYTE15_12.build();

         SCU_TEMPERATURE_TEST_ENA = SCU_TEMPERATURE_TEST_ENA_reg::type_id::create("SCU_TEMPERATURE_TEST_ENA");
         SCU_TEMPERATURE_TEST_ENA.configure(this);
         SCU_TEMPERATURE_TEST_ENA.build();

         SCU_TEMPERATURE_TEST_DIGIT0 = SCU_TEMPERATURE_TEST_DIGIT0_reg::type_id::create("SCU_TEMPERATURE_TEST_DIGIT0");
         SCU_TEMPERATURE_TEST_DIGIT0.configure(this);
         SCU_TEMPERATURE_TEST_DIGIT0.build();

         SCU_TEMPERATURE_TEST_DIGIT1 = SCU_TEMPERATURE_TEST_DIGIT1_reg::type_id::create("SCU_TEMPERATURE_TEST_DIGIT1");
         SCU_TEMPERATURE_TEST_DIGIT1.configure(this);
         SCU_TEMPERATURE_TEST_DIGIT1.build();

         SCU_map = create_map("SCU_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = SCU_map;

         SCU_map.add_reg(SCU_ZU_DATA_ENA, 'h0, "RW");
         SCU_map.add_reg(SCU_DTI_READ_ENA, 'h4, "RW");
         SCU_map.add_reg(SCU_FSM_RST, 'h8, "RW");
         SCU_map.add_reg(SCU_OLEDBYTE3_0, 'h10, "RW");
         SCU_map.add_reg(SCU_OLEDBYTE7_4, 'h14, "RW");
         SCU_map.add_reg(SCU_OLEDBYTE11_8, 'h18, "RW");
         SCU_map.add_reg(SCU_OLEDBYTE15_12, 'h1c, "RW");
         SCU_map.add_reg(SCU_TEMPERATURE_TEST_ENA, 'h28, "RW");
         SCU_map.add_reg(SCU_TEMPERATURE_TEST_DIGIT0, 'h2c, "RW");
         SCU_map.add_reg(SCU_TEMPERATURE_TEST_DIGIT1, 'h30, "RW");

         lock_model();
      endfunction


      // Function: sample
      // 
      function void sample(uvm_reg_addr_t offset, bit is_read, uvm_reg_map  map);
         if(get_coverage(UVM_CVR_ADDR_MAP)) begin
            if(map.get_name() == "SCU_map") begin
               SCU_map_cg.sample(offset, is_read);
            end
         end
      endfunction: sample

   endclass



   //--------------------------------------------------------------------
   // Class: AUI_module_AUI_map_coverage
   // 
   // Coverage for the 'AUI_map' in 'AUI_module'
   //--------------------------------------------------------------------

   class AUI_module_AUI_map_coverage extends uvm_object;
      `uvm_object_utils(AUI_module_AUI_map_coverage)

      covergroup ra_cov(string name) with function sample(uvm_reg_addr_t addr, bit is_read);

         option.per_instance = 1;
         option.name = name; 

         ADDR: coverpoint addr {
            bins AUI_RESET = {'h1020};
            bins AUI_AURORA_LOOPBACK = {'h1040};
            bins AUI_AURORA_RESET = {'h1044};
            bins AUI_AURORA_GT_RESET = {'h1048};
            bins AUI_AURORA_FIFO_TX_WRITE_ENABLE = {'h1054};
            bins AUI_AURORA_ACCESS_LOOP_ENA = {'h1058};
         }

         RW: coverpoint is_read {
            bins RD = {1};
            bins WR = {0};
         }

         ACCESS: cross ADDR, RW;

      endgroup: ra_cov

      function new(string name = "AUI_module_AUI_map_coverage");
         ra_cov = new(name);
      endfunction: new

      function void sample(uvm_reg_addr_t offset, bit is_read);
         ra_cov.sample(offset, is_read);
      endfunction: sample

   endclass: AUI_module_AUI_map_coverage



   //--------------------------------------------------------------------
   // Class: AUI_module
   // 
   // Block  registers
   //--------------------------------------------------------------------

   class AUI_module extends uvm_reg_block;
      `uvm_object_utils(AUI_module)

      rand AUI_RESET_reg AUI_RESET; 
      rand AUI_AURORA_LOOPBACK_reg AUI_AURORA_LOOPBACK; 
      rand AUI_AURORA_RESET_reg AUI_AURORA_RESET; 
      rand AUI_AURORA_GT_RESET_reg AUI_AURORA_GT_RESET; 
      rand AUI_AURORA_FIFO_TX_WRITE_ENABLE_reg AUI_AURORA_FIFO_TX_WRITE_ENABLE; 
      rand AUI_AURORA_ACCESS_LOOP_ENA_reg AUI_AURORA_ACCESS_LOOP_ENA; 

      uvm_reg_map AUI_map; 
      AUI_module_AUI_map_coverage AUI_map_cg;


      // Function: new
      // 
      function new(string name = "AUI_module");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();

         if(has_coverage(UVM_CVR_ADDR_MAP)) begin
            AUI_map_cg = AUI_module_AUI_map_coverage::type_id::create("AUI_map_cg");
            AUI_map_cg.ra_cov.set_inst_name(this.get_full_name());
            void'(set_coverage(UVM_CVR_ADDR_MAP));
         end
         AUI_RESET = AUI_RESET_reg::type_id::create("AUI_RESET");
         AUI_RESET.configure(this);
         AUI_RESET.build();

         AUI_AURORA_LOOPBACK = AUI_AURORA_LOOPBACK_reg::type_id::create("AUI_AURORA_LOOPBACK");
         AUI_AURORA_LOOPBACK.configure(this);
         AUI_AURORA_LOOPBACK.build();

         AUI_AURORA_RESET = AUI_AURORA_RESET_reg::type_id::create("AUI_AURORA_RESET");
         AUI_AURORA_RESET.configure(this);
         AUI_AURORA_RESET.build();

         AUI_AURORA_GT_RESET = AUI_AURORA_GT_RESET_reg::type_id::create("AUI_AURORA_GT_RESET");
         AUI_AURORA_GT_RESET.configure(this);
         AUI_AURORA_GT_RESET.build();

         AUI_AURORA_FIFO_TX_WRITE_ENABLE = AUI_AURORA_FIFO_TX_WRITE_ENABLE_reg::type_id::create("AUI_AURORA_FIFO_TX_WRITE_ENABLE");
         AUI_AURORA_FIFO_TX_WRITE_ENABLE.configure(this);
         AUI_AURORA_FIFO_TX_WRITE_ENABLE.build();

         AUI_AURORA_ACCESS_LOOP_ENA = AUI_AURORA_ACCESS_LOOP_ENA_reg::type_id::create("AUI_AURORA_ACCESS_LOOP_ENA");
         AUI_AURORA_ACCESS_LOOP_ENA.configure(this);
         AUI_AURORA_ACCESS_LOOP_ENA.build();

         AUI_map = create_map("AUI_map", 'h0, 1, UVM_LITTLE_ENDIAN, 1);
         default_map = AUI_map;

         AUI_map.add_reg(AUI_RESET, 'h1020, "RW");
         AUI_map.add_reg(AUI_AURORA_LOOPBACK, 'h1040, "RW");
         AUI_map.add_reg(AUI_AURORA_RESET, 'h1044, "RW");
         AUI_map.add_reg(AUI_AURORA_GT_RESET, 'h1048, "RW");
         AUI_map.add_reg(AUI_AURORA_FIFO_TX_WRITE_ENABLE, 'h1054, "RW");
         AUI_map.add_reg(AUI_AURORA_ACCESS_LOOP_ENA, 'h1058, "RW");

         lock_model();
      endfunction


      // Function: sample
      // 
      function void sample(uvm_reg_addr_t offset, bit is_read, uvm_reg_map  map);
         if(get_coverage(UVM_CVR_ADDR_MAP)) begin
            if(map.get_name() == "AUI_map") begin
               AUI_map_cg.sample(offset, is_read);
            end
         end
      endfunction: sample

   endclass



   //--------------------------------------------------------------------
   // Class: top_PSIF_rw
   // 
   // PSIF  instance
   //--------------------------------------------------------------------

   class top_PSIF_rw extends uvm_reg_block;
      `uvm_object_utils(top_PSIF_rw)

      rand ODI_module ODI; 
      rand DTI_module DTI; 
      rand ZU_module ZU; 
      rand SCU_module SCU; 
      rand AUI_module AUI; 
      ZUPACKET_mem ZUPACKET; 
      ZUKEY_mem ZUKEY; 

      uvm_reg_map top_if_map; 


      // Function: new
      // 
      function new(string name = "top_PSIF_rw");
         super.new(name, build_coverage(UVM_CVR_ALL));
      endfunction


      // Function: build
      // 
      virtual function void build();
         ODI = ODI_module::type_id::create("ODI");
         ODI.configure(this);
         ODI.build();

         DTI = DTI_module::type_id::create("DTI");
         DTI.configure(this);
         DTI.build();

         ZU = ZU_module::type_id::create("ZU");
         ZU.configure(this);
         ZU.build();

         SCU = SCU_module::type_id::create("SCU");
         SCU.configure(this);
         SCU.build();

         AUI = AUI_module::type_id::create("AUI");
         AUI.configure(this);
         AUI.build();

         ZUPACKET = ZUPACKET_mem::type_id::create("ZUPACKET");
         ZUPACKET.configure(this);

         ZUKEY = ZUKEY_mem::type_id::create("ZUKEY");
         ZUKEY.configure(this);

         top_if_map = create_map("top_if_map", 'h0, 4, UVM_LITTLE_ENDIAN, 1);
         default_map = top_if_map;

         top_if_map.add_submap(ODI.ODI_map, 'h10000);
         top_if_map.add_submap(DTI.DTI_map, 'h20000);
         top_if_map.add_submap(ZU.ZU_map, 'h30000);
         top_if_map.add_submap(SCU.SCU_map, 'h40000);
         top_if_map.add_submap(AUI.AUI_map, 'h50000);
         top_if_map.add_mem(ZUPACKET, 'h600000, "RW");
         top_if_map.add_mem(ZUKEY, 'h800000, "RW");

         lock_model();
      endfunction
   endclass


endpackage
